version: '3.8'

services:
  itis-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://itis_user:Sita_Secure_Pass2026@postgres:5432/itis_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=itis_production_jwt_rsa_2026_secret_key
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: itis_user
      POSTGRES_PASSWORD: Sita_Secure_Pass2026
      POSTGRES_DB: itis_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
